functionsDirectory = "/Users/martinmana/Documents/Projects/f925-26/netlify/functions"
functionsDirectoryOrigin = "config"
headersOrigin = "config"
plugins = []

[build]
publish = "/Users/martinmana/Documents/Projects/f925-26/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/Users/martinmana/Documents/Projects/f925-26/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[dev]
command = "npm run dev"
targetPort = 5173.0

[functions]

[functions."*"]
node_bundler = "esbuild"

[[headers]]
for = "assets/*.pdf"

[headers.values]
Content-Type = "application/pdf"

[[redirects]]
from = "/work"
to = "/portfolio"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/stuff"
to = "/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/stuff/llms"
to = "/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/services/ux-ui-design"
to = "/services/website-products"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/services/graphic-design"
to = "/services/website-products"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/services/website-development"
to = "/services/website-products"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/services/app-development"
to = "/services/website-products"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/services/ai-solutions"
to = "/services/ai-agents"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/404"
to = "/404.html"
status = 404.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]