#!/usr/bin/env python3
"""Enrich dealers.json with everything a preview site needs that the hard data doesn't give:
opening hours in the platform's shape, partner brands matched to UNIFY's premade set, a
sensible default service list, and per-dealer copy (tagline, hero, about page, "what makes
us special", SEO meta) written from the facts we have.

Copy is generated by `claude -p` (Haiku), one dealer per call, strict JSON out. Facts in →
(`--cache-only` skips writing dealers.json so several can run at once; a plain run merges.)
copy out; nothing invented beyond what a shop in that town with those brands would say.
Cached in content/<slug>.json so re-runs only write missing dealers. Pass --force to redo,
--only slug to do one.
"""
import json, re, subprocess, sys, time
from pathlib import Path

HERE = Path(__file__).parent
CONTENT = HERE / 'content'; CONTENT.mkdir(exist_ok=True)
dealers = json.load(open(HERE / 'dealers.json'))
TARGET_SEGMENTS = {'no-site', 'warm'}
force = '--force' in sys.argv
only = sys.argv[sys.argv.index('--only') + 1] if '--only' in sys.argv else None
if '--all' in sys.argv: TARGET_SEGMENTS = {s['segment'] for s in dealers if s['segment'] != 'closed'}

# ---- hours: locator labels like "Monday - Friday: 8:30am - 5:30pm" -> per-day {open, close, closed}
DAYS = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']
DAY_IDX = {'monday': 0, 'tuesday': 1, 'wednesday': 2, 'thursday': 3, 'friday': 4, 'saturday': 5, 'sunday': 6}
def to24(t):
    t = t.strip().lower().replace('.', ':')
    m = re.match(r'(\d{1,2})(?::(\d{2}))?\s*(am|pm)?', t)
    if not m: return None
    h, mi, ap = int(m.group(1)), int(m.group(2) or 0), m.group(3)
    if ap == 'pm' and h != 12: h += 12
    if ap == 'am' and h == 12: h = 0
    return f'{h:02d}:{mi:02d}'
def parse_hours(loc):
    out = {d: {'open': '', 'close': '', 'closed': True} for d in DAYS}
    if not loc: return None
    for v in loc.values():
        label = (v.get('label') or '').lower(); hrs = (v.get('hours') or '').strip()
        names = re.findall(r'monday|tuesday|wednesday|thursday|friday|saturday|sunday', label)
        if not names: continue
        if '-' in label and len(names) == 2:
            a, b = DAY_IDX[names[0]], DAY_IDX[names[1]]; idxs = list(range(a, b + 1))
        else:
            idxs = [DAY_IDX[n] for n in names]
        if re.search(r'closed', hrs, re.I) or not hrs:
            continue
        m = re.match(r'(.+?)\s*[-–]\s*(.+)', hrs)
        if not m: continue
        o, c = to24(m.group(1)), to24(m.group(2))
        if not o or not c: continue
        for i in idxs: out[DAYS[i]] = {'open': o, 'close': c, 'closed': False}
    # weekday gap fill: the locator often lists Monday separately from Tue–Fri; if any weekday is
    # missing but others are set, copy the most common weekday hours into it.
    wk = [out[d] for d in DAYS[:5] if not out[d]['closed']]
    if wk and any(out[d]['closed'] for d in DAYS[:5]):
        common = max(wk, key=lambda h: sum(1 for w in wk if w == h))
        for d in DAYS[:5]:
            if out[d]['closed']: out[d] = dict(common)
    out['useCustomPerDay'] = True
    return out

# ---- partners: match locator brand names to UNIFY premades (others kept as custom names)
PREMADE = ['Honda', 'Masport', 'Cub Cadet', 'Hansa', 'Gravely', 'Walker Mowers', 'Wet & Forget', 'Done & Dusted']
def match_partners(brands):
    sel, custom = [], []
    for b in brands or []:
        bl = b.lower()
        if 'stihl' in bl: continue
        hit = next((p for p in PREMADE if p.lower().split()[0] in bl), None)
        if hit and hit not in sel: sel.append(hit)
        elif not hit and b not in custom: custom.append(re.sub(r'\s*(power equipment|bbqs?)$', '', b, flags=re.I).strip())
    return sel, custom

# ---- services: sensible defaults; chainsaw + repairs + diagnostics always; ride-on when they stock mowers
def default_services(brands):
    keys = ['chainsaw', 'repairs', 'diagnostics', 'warranty', 'preseason']
    if any(re.search(r'masport|honda|cub cadet|rover|hustler|walker|gravely|john deere|lawnmaster', b, re.I) for b in brands or []):
        keys.insert(1, 'rideon')
    keys.append('pickup')
    return keys[:6], keys[:3]

PROMPT = """You write website copy for a small-town New Zealand outdoor-power-equipment shop. Warm, plain, confident, no marketing fluff, NZ English (no hyphens where a comma or full stop will do, no exclamation marks, never the words "passionate", "solutions", "elevate", "unparalleled"). Write in first person plural ("we"). Only use the facts given; do not invent history, awards, years, staff names or services not implied by the facts. If owners are named, you may name them once in the about text. If there is a source blurb, keep its facts and improve the writing; do not copy sentences verbatim.

FACTS
Store: {store}
Town: {town} ({region} region, New Zealand)
Owners: {owners}
Brands stocked: {brands}
Opening days: {days}
Source blurb (may be empty): {blurb}
Text from their current website (may be empty; this is the dealer's own story, keep its facts, people and services, improve the writing): {sitetext}

Return ONLY a JSON object, no prose, with exactly these keys:
{{
 "tagline": "6–10 words, the shop in one line, no full stop",
 "heroHeading": "3–6 words",
 "heroSubheading": "one sentence, max 20 words, what the shop is for locals",
 "aboutHtml": "2 or 3 short paragraphs as <p>…</p>, 120–180 words total: who we are, what we do (sales, servicing, parts, advice), why locals come to us. End with an invitation to come in.",
 "whatMakesUsSpecial": ["4 short items, 4–9 words each, concrete not slogans"],
 "servicesIntro": "one sentence, max 25 words, introducing the workshop",
 "metaTitle": "STIHL SHOP {short} | outdoor power equipment in {town}",
 "metaDescription": "max 155 characters"
}}"""

def facts_for(d):
    st = d.get('stihlshop') or {}
    owners = ', '.join(f"{o['first']} {o['last']}".strip() for o in d.get('owners') or []) or 'not given'
    brands = ', '.join(st.get('brands') or []) or ('STIHL' if not st.get('brands') else '')
    hrs = st.get('hours') or {}
    days = '; '.join(f"{v.get('label')}: {v.get('hours')}" for v in hrs.values()) or 'not given'
    stp = HERE / 'sitetext' / f"{d['slug']}.md"
    sitetext = '(none)'
    if stp.exists():
        raw = stp.read_text()
        if not raw.startswith('ERROR'):
            # drop nav/link lists and boilerplate lines; keep sentences
            lines = [l.strip() for l in raw.splitlines() if len(l.strip()) > 40 and not l.strip().startswith(('*', '[', '#', '|'))]
            sitetext = ' '.join(lines)[:2500] or '(none)'
    return dict(store=d['store'], short=d['shortName'], town=d['town'], region=d['region'], owners=owners,
                brands=brands or 'STIHL', days=days, blurb=(st.get('description') or '').strip()[:900] or '(none)', sitetext=sitetext)

def gen_copy(d):
    prompt = PROMPT.format(**facts_for(d))
    for attempt in range(3):
        r = subprocess.run(['claude', '-p', '--model', 'haiku', '--output-format', 'text', prompt], capture_output=True, text=True, timeout=180)
        txt = r.stdout.strip()
        m = re.search(r'\{.*\}', txt, re.S)
        if m:
            try:
                obj = json.loads(m.group(0))
                need = ['tagline', 'heroHeading', 'heroSubheading', 'aboutHtml', 'whatMakesUsSpecial', 'servicesIntro', 'metaTitle', 'metaDescription']
                if all(k in obj for k in need) and isinstance(obj['whatMakesUsSpecial'], list):
                    obj['whatMakesUsSpecial'] = obj['whatMakesUsSpecial'][:5]
                    obj['metaDescription'] = obj['metaDescription'][:155]
                    return obj
            except json.JSONDecodeError:
                pass
        time.sleep(2)
    raise RuntimeError(f"no valid copy for {d['slug']}: {txt[:200]}")

done, skipped, failed = 0, 0, []
for d in dealers:
    if d['segment'] not in TARGET_SEGMENTS and d['slug'] != only: continue
    if only and d['slug'] != only: continue
    st = d.get('stihlshop') or {}
    brands = st.get('brands')
    if not brands:
        # no brands in the locator blurb: read them off their own website text when we have it
        stp = HERE / 'sitetext' / f"{d['slug']}.md"
        if stp.exists():
            txt = stp.read_text()
            brands = [b for b in PREMADE + ['Rover', 'Hustler', 'Weber', 'Husqvarna', 'Victa', 'Kubota', 'Toro', 'Echo'] if re.search(r'\b' + re.escape(b if '&' in b else b.split()[0]) + r'\b', txt, re.I)] or None
            if brands: d.setdefault('notes', ''); d['brandsSource'] = 'own website'
    sel, custom = match_partners(brands)
    svc, featured = default_services(brands)
    hours = parse_hours(st.get('hours'))
    cache = CONTENT / f"{d['slug']}.json"
    if cache.exists() and not force:
        copy = json.load(open(cache)); skipped += 1
    else:
        try:
            copy = gen_copy(d); json.dump(copy, open(cache, 'w'), indent=2, ensure_ascii=False); done += 1
            print('✓', d['shortName'], '—', copy['tagline'])
        except Exception as e:
            failed.append((d['slug'], str(e)[:120])); continue
    d['preview'] = {
        'hours': hours,
        'hoursSource': 'stihlshop.co.nz locator' if hours else 'default weekdays 8–5',
        'partners': {'selectedPremadeNames': sel, 'custom': custom},
        'services': {'selectedPremadeKeys': svc, 'featuredKeys': featured},
        'heroImage': f"images/{d['slug']}.jpg",
        'googleMapsQuery': f"{d['store']}, {st.get('address') or d['address']}",
        'copy': copy,
        'defaults': {  # things we could not know — shown on the preview, easy to change at onboarding
            'social': 'none set',
            'reviews': 'none — the preview shows the reviews block empty',
            'team': 'none — owners named in About only',
            'inStoreProducts': 'none — brands shown as partner logos instead',
        },
    }

if '--cache-only' not in sys.argv:  # parallel runs: write content/ only, merge later with a plain run
    json.dump(dealers, open(HERE / 'dealers.json', 'w'), indent=2, ensure_ascii=False)
print(f'generated {done}, cached {skipped}, failed {len(failed)}')
for f in failed: print('  FAILED', *f)
